### DISCUSSION TITLE
Basic Authorization fails?

### DISCUSSION THREAD

**Discussion by rct225** [JamesIves/fetch-api-data-action#1055] [Q&A]
I was using this action to download and store some data with an API.  Here's my workflow file: 

```
name: Refresh Feed
on:
  [push]
  # schedule:
  #   - cron: 10 15 * * 0-6
jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Fetch API Data 📦
        uses: JamesIves/fetch-api-data-action@v2.3.0
        with:
          endpoint: 'http://uscms-openproject.k8s.accre.vanderbilt.edu/api/v3/work_packages?filters=[{"dueDate": { "operator": "<>d", "values": ["2023-01-01", "2023-12-31"] }}]&pageSize=1000'
          configuration: '{ "method": "GET", "headers": {"Authorization": "Basic ${{ secrets.OPENPROJ_ID }}"} }'
          save-location: data
          save-name: all_results
          set-output: false

      - name: Build and Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main # Pushes the updates to the main branch.
          folder: data # The location of the data.json file saved by the Fetch API Data action.
          target-folder: data # Saves the data into the 'data' directory on the main branch.

      - name: Build and Deploy to custom gantt
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: openproject_data
          repository-name: uscms-software-and-computing/uscms_custom_gantt
          token: ${{ secrets.DEPLOY_KEY }}
          folder: data
          target-folder: data

      - name: Build and Deploy to Project Dashboard
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          repository-name: uscms-software-and-computing/project-dashboard
          token: ${{ secrets.PROJECT_DASHBOARD_DEPLOY }}
          folder: data
          target-folder: data
```

It was working with Basic Auth and then suddenly stopped.  The OPENPROJ_ID secret exists and contains the proper key.  Is there something I'm missing?
