### DISCUSSION TITLE
2.0.0

### DISCUSSION THREAD

**Discussion by JamesIves** [JamesIves/fetch-api-data-action#442] [Releases]
# Version 2.0.0 🎉 

It's been long overdue, but version 2.0.0 is here.

## Major Changes

* The action now uses lowercase `snake-case` for parameters instead of uppercase with underscores `LIKE_THIS`. You can see an example of this below:

```yml
name: Refresh Feed
on: [push]
jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data 📦
        uses: JamesIves/fetch-api-data-action@2.0.0
        with:
          endpoint: https://example.com
          configuration: '{ "method": "GET", "headers": {"Authorization": "Bearer ${{ secrets.API_TOKEN }}"} }'
          save-name: youtube
```

* Added a `debug` flag which allows you to log your way through the workflow. With this flag turned on you'll see all API responses the action receives in the terminal. You can find details surrounding this in the README.
* Migrated to Node 14 from 12 for development.

## Minor Changes

* Tons of dependency and security updates from third party libraries.
* Migrated ESLint/Prettier config.
* Added workflow helpers for quicker releases.
* Improved integration testing.
* Added GitHub Discussions support.
* Added Sponsors section to README. 

<hr /><em>This discussion was created from the release <a href='https://github.com/JamesIves/fetch-api-data-action/releases/tag/2.0.0'>2.0.0</a>.</em>
