### DISCUSSION TITLE
Auth token from token endpoint is rejected during gha workflow but not locally.

### DISCUSSION THREAD

**Discussion by LwrncLiu** [JamesIves/fetch-api-data-action#819] [Q&A]
I'm attempting to return the data from the strava api that requires authentication prior to the api call. The full .yml file can be seen [here](https://github.com/LwrncLiu/running_mu_biao/blob/main/.github/workflows/fetch_strava.yml), but I have what I believe to be relevant below. 

After running the workflow, the token-endpoint returns an object with access_token as a key. This is confirmed when I run the action with debug on. However, the access_token value based to the endpoint returns the following error: Error: {"message":"Authorization Error","errors":[{"resource":"Athlete","field":"access_token","code":"invalid"}]}. 

However, if I take the access_token value and call the same api call locally via Postman, data is returned without error. 

I'm not sure if this behavior is a Strava issue, a github action "environment" issue, or a potential bug with this github action. Any guidance is appreciated :').

```
    - name: Fetch data
      uses: JamesIves/fetch-api-data-action@v2
      with:
        token-endpoint: https://www.strava.com/api/v3/oauth/token
        token-configuration: '{ "method":"POST", "headers": {"Accept": "application/json, text/plain, */*", "Content-Type": "application/json"}, "body": {"client_id": "99458", "client_secret": "${{ secrets.STRAVA_CLIENT_SECRET }}", "refresh_token": "${{ secrets.STRAVA_REFRESH_TOKEN }}", "grant_type": "refresh_token", "redirect_uri": "http://localhost"} }'
        endpoint: https://www.strava.com/api/v3/athlete/activities/
        configuration: '{ "method": "GET", "headers": {"Authorization": "Bearer {{{ data.access_token }}}"} }'
```

**Comment by JamesIves** [comment]
Can you try the following config? 🤔  I use this action for Strava, and this is what I have configured which works.

```
      - name: Fetch API Data 📦
        uses: JamesIves/fetch-api-data-action@releases/v1
        with:
          TOKEN_ENDPOINT: https://www.strava.com/api/v3/oauth/token
          TOKEN_CONFIGURATION: '{ "method": "POST", "body": {"client_id": "${{ secrets.client_id }}", "client_secret": "${{ secrets.client_secret }}"} }'
          ENDPOINT: https://www.strava.com/api/v3/athlete/activities
          CONFIGURATION: '{ "method": "GET", "headers": {"Authorization": "Bearer {{{ data.access_token }}}"} }'
          SAVE_NAME: strava
```

Based on [this blog post](https://jamesiv.es/blog/github/actions/2020/03/07/fetching-authenticated-api-data)
