### ISSUE TITLE
Argument list too long when fetching large JSON file

### ISSUE THREAD

**Issue by Kerakis** [JamesIves/fetch-api-data-action#534]
## Describe the bug
I receive the error "Error: An error occurred trying to start process '/home/runner/runners/2.288.1/externals/node12/bin/node' with working directory '/home/runner/work/mtg-art-game/mtg-art-game'. Argument list too long" when fetching a large json catalog of card names.

## Reproduction Steps
The workflow fires successfully with other API calls, but always fails with this one: https://api.scryfall.com/catalog/card-names

## Logs

[logs_32.zip](https://github.com/JamesIves/fetch-api-data-action/files/8192905/logs_32.zip)

## Workflow

```
name: Update Card Names Catalog
on:
  schedule:
    - cron: 0 0 * * SUN
     # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  update-cards:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Fetch API Data
        uses: JamesIves/fetch-api-data-action@v2.2.0
        with:
          endpoint: https://api.scryfall.com/catalog/card-names
          configuration: '{ "method": "GET" }'
          save-location: assets
          save-name: test

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: main # Pushes the updates to the main branch.
          folder: assets # The location of the data.json file saved by the Fetch API Data action.
          target-folder: assets # Saves the data into the 'data' directory on the main branch.
```

## Additional Comments

Is there a maximum JSON length that can work with this workflow?

**Comment by JamesIves** [comment]
Can you provide a copy of the workflow logs from the action? I see you attached a log but I'd much prefer it if you posted it in plain text within the issue.

**Comment by Kerakis** [comment]
Of course. I apologize if this is an obvious oversight. I'm a bit new to all of this.

2022-03-06T15:28:27.1233039Z Requested labels: ubuntu-latest
2022-03-06T15:28:27.1233103Z Job defined at: Kerakis/mtg-art-game/.github/workflows/test.yml@refs/heads/main
2022-03-06T15:28:27.1233129Z Waiting for a runner to pick up this job...
2022-03-06T15:28:27.4859291Z Job is waiting for a hosted runner to come online.
2022-03-06T15:28:30.8212828Z Job is about to start running on the hosted runner: GitHub Actions 2 (hosted)
2022-03-06T15:28:33.6922033Z Current runner version: '2.288.1'
2022-03-06T15:28:33.6954453Z ##[group]Operating System
2022-03-06T15:28:33.6954954Z Ubuntu
2022-03-06T15:28:33.6955266Z 20.04.4
2022-03-06T15:28:33.6955590Z LTS
2022-03-06T15:28:33.6955880Z ##[endgroup]
2022-03-06T15:28:33.6956237Z ##[group]Virtual Environment
2022-03-06T15:28:33.6956555Z Environment: ubuntu-20.04
2022-03-06T15:28:33.6956898Z Version: 20220227.1
2022-03-06T15:28:33.6957405Z Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20220227.1/images/linux/Ubuntu2004-Readme.md
2022-03-06T15:28:33.6958065Z Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20220227.1
2022-03-06T15:28:33.6958513Z ##[endgroup]
2022-03-06T15:28:33.6958826Z ##[group]Virtual Environment Provisioner
2022-03-06T15:28:33.6959195Z 1.0.0.0-main-20220225-1
2022-03-06T15:28:33.6959488Z ##[endgroup]
2022-03-06T15:28:33.6960457Z ##[group]GITHUB_TOKEN Permissions
2022-03-06T15:28:33.6961070Z Actions: write
2022-03-06T15:28:33.6961501Z Checks: write
2022-03-06T15:28:33.6961893Z Contents: write
2022-03-06T15:28:33.6962215Z Deployments: write
2022-03-06T15:28:33.6962553Z Discussions: write
2022-03-06T15:28:33.6962820Z Issues: write
2022-03-06T15:28:33.6963132Z Metadata: read
2022-03-06T15:28:33.6963401Z Packages: write
2022-03-06T15:28:33.6963729Z Pages: write
2022-03-06T15:28:33.6964053Z PullRequests: write
2022-03-06T15:28:33.6964352Z RepositoryProjects: write
2022-03-06T15:28:33.6964740Z SecurityEvents: write
2022-03-06T15:28:33.6965016Z Statuses: write
2022-03-06T15:28:33.6965329Z ##[endgroup]
2022-03-06T15:28:33.6969361Z Secret source: Actions
2022-03-06T15:28:33.6969901Z Prepare workflow directory
2022-03-06T15:28:33.7815839Z Prepare all required actions
2022-03-06T15:28:33.8004010Z Getting action download info
2022-03-06T15:28:34.0430320Z Download action repository 'actions/checkout@v2' (SHA:ec3a7ce113134d7a93b817d10a8272cb61118579)
2022-03-06T15:28:34.9529588Z Download action repository 'JamesIves/fetch-api-data-action@v2.2.0' (SHA:c38518c0358c6a522f0d4880212b65963e2d6574)
2022-03-06T15:28:35.8117289Z Download action repository 'JamesIves/github-pages-deploy-action@v4.2.5' (SHA:830e6a4f7c81743c52f3fed0ac67428feff9620a)
2022-03-06T15:28:37.1608640Z ##[group]Run actions/checkout@v2
2022-03-06T15:28:37.1608925Z with:
2022-03-06T15:28:37.1609156Z   persist-credentials: false
2022-03-06T15:28:37.1609424Z   repository: Kerakis/mtg-art-game
2022-03-06T15:28:37.1609931Z   token: ***
2022-03-06T15:28:37.1610139Z   ssh-strict: true
2022-03-06T15:28:37.1610327Z   clean: true
2022-03-06T15:28:37.1610528Z   fetch-depth: 1
2022-03-06T15:28:37.1610710Z   lfs: false
2022-03-06T15:28:37.1610909Z   submodules: false
2022-03-06T15:28:37.1611118Z ##[endgroup]
2022-03-06T15:28:37.4130283Z Syncing repository: Kerakis/mtg-art-game
2022-03-06T15:28:37.4132000Z ##[group]Getting Git version info
2022-03-06T15:28:37.4132511Z Working directory is '/home/runner/work/mtg-art-game/mtg-art-game'
2022-03-06T15:28:37.4133011Z [command]/usr/bin/git version
2022-03-06T15:28:37.4307015Z git version 2.35.1
2022-03-06T15:28:37.4308647Z ##[endgroup]
2022-03-06T15:28:37.4309049Z Deleting the contents of '/home/runner/work/mtg-art-game/mtg-art-game'
2022-03-06T15:28:37.4312312Z ##[group]Initializing the repository
2022-03-06T15:28:37.4312733Z [command]/usr/bin/git init /home/runner/work/mtg-art-game/mtg-art-game
2022-03-06T15:28:37.4382485Z hint: Using 'master' as the name for the initial branch. This default branch name
2022-03-06T15:28:37.4383488Z hint: is subject to change. To configure the initial branch name to use in all
2022-03-06T15:28:37.4384442Z hint: of your new repositories, which will suppress this warning, call:
2022-03-06T15:28:37.4384761Z hint: 
2022-03-06T15:28:37.4385233Z hint: 	git config --global init.defaultBranch <name>
2022-03-06T15:28:37.4385489Z hint: 
2022-03-06T15:28:37.4385844Z hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
2022-03-06T15:28:37.4386316Z hint: 'development'. The just-created branch can be renamed via this command:
2022-03-06T15:28:37.4386937Z hint: 
2022-03-06T15:28:37.4387180Z hint: 	git branch -m <name>
2022-03-06T15:28:37.4396710Z Initialized empty Git repository in /home/runner/work/mtg-art-game/mtg-art-game/.git/
2022-03-06T15:28:37.4408834Z [command]/usr/bin/git remote add origin https://github.com/Kerakis/mtg-art-game
2022-03-06T15:28:37.4451334Z ##[endgroup]
2022-03-06T15:28:37.4452537Z ##[group]Disabling automatic garbage collection
2022-03-06T15:28:37.4456413Z [command]/usr/bin/git config --local gc.auto 0
2022-03-06T15:28:37.4492029Z ##[endgroup]
2022-03-06T15:28:37.4511875Z ##[group]Setting up auth
2022-03-06T15:28:37.4562922Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2022-03-06T15:28:37.4600314Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2022-03-06T15:28:37.4969378Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2022-03-06T15:28:37.5005734Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2022-03-06T15:28:37.5244233Z [command]/usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
2022-03-06T15:28:37.5287430Z ##[endgroup]
2022-03-06T15:28:37.5290322Z ##[group]Fetching the repository
2022-03-06T15:28:37.5295475Z [command]/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +688dfd95b901f2e0bc6409843990242107164377:refs/remotes/origin/main
2022-03-06T15:28:37.9178341Z remote: Enumerating objects: 25, done.        
2022-03-06T15:28:37.9180371Z remote: Counting objects:   4% (1/25)        
2022-03-06T15:28:37.9180711Z remote: Counting objects:   8% (2/25)        
2022-03-06T15:28:37.9180982Z remote: Counting objects:  12% (3/25)        
2022-03-06T15:28:37.9181264Z remote: Counting objects:  16% (4/25)        
2022-03-06T15:28:37.9181521Z remote: Counting objects:  20% (5/25)        
2022-03-06T15:28:37.9182108Z remote: Counting objects:  24% (6/25)        
2022-03-06T15:28:37.9182384Z remote: Counting objects:  28% (7/25)        
2022-03-06T15:28:37.9182639Z remote: Counting objects:  32% (8/25)        
2022-03-06T15:28:37.9182874Z remote: Counting objects:  36% (9/25)        
2022-03-06T15:28:37.9183133Z remote: Counting objects:  40% (10/25)        
2022-03-06T15:28:37.9183377Z remote: Counting objects:  44% (11/25)        
2022-03-06T15:28:37.9183631Z remote: Counting objects:  48% (12/25)        
2022-03-06T15:28:37.9183886Z remote: Counting objects:  52% (13/25)        
2022-03-06T15:28:37.9184123Z remote: Counting objects:  56% (14/25)        
2022-03-06T15:28:37.9184372Z remote: Counting objects:  60% (15/25)        
2022-03-06T15:28:37.9184608Z remote: Counting objects:  64% (16/25)        
2022-03-06T15:28:37.9184860Z remote: Counting objects:  68% (17/25)        
2022-03-06T15:28:37.9185104Z remote: Counting objects:  72% (18/25)        
2022-03-06T15:28:37.9185348Z remote: Counting objects:  76% (19/25)        
2022-03-06T15:28:37.9185601Z remote: Counting objects:  80% (20/25)        
2022-03-06T15:28:37.9185837Z remote: Counting objects:  84% (21/25)        
2022-03-06T15:28:37.9186085Z remote: Counting objects:  88% (22/25)        
2022-03-06T15:28:37.9186324Z remote: Counting objects:  92% (23/25)        
2022-03-06T15:28:37.9186567Z remote: Counting objects:  96% (24/25)        
2022-03-06T15:28:37.9186823Z remote: Counting objects: 100% (25/25)        
2022-03-06T15:28:37.9187074Z remote: Counting objects: 100% (25/25), done.        
2022-03-06T15:28:37.9187365Z remote: Compressing objects:   4% (1/23)        
2022-03-06T15:28:37.9192614Z remote: Compressing objects:   8% (2/23)        
2022-03-06T15:28:37.9193824Z remote: Compressing objects:  13% (3/23)        
2022-03-06T15:28:37.9194107Z remote: Compressing objects:  17% (4/23)        
2022-03-06T15:28:37.9260782Z remote: Compressing objects:  21% (5/23)        
2022-03-06T15:28:37.9261102Z remote: Compressing objects:  26% (6/23)        
2022-03-06T15:28:37.9261374Z remote: Compressing objects:  30% (7/23)        
2022-03-06T15:28:37.9278491Z remote: Compressing objects:  34% (8/23)        
2022-03-06T15:28:37.9285771Z remote: Compressing objects:  39% (9/23)        
2022-03-06T15:28:37.9293248Z remote: Compressing objects:  43% (10/23)        
2022-03-06T15:28:37.9358023Z remote: Compressing objects:  47% (11/23)        
2022-03-06T15:28:37.9638321Z remote: Compressing objects:  52% (12/23)        
2022-03-06T15:28:37.9638754Z remote: Compressing objects:  56% (13/23)        
2022-03-06T15:28:37.9639073Z remote: Compressing objects:  60% (14/23)        
2022-03-06T15:28:37.9639374Z remote: Compressing objects:  65% (15/23)        
2022-03-06T15:28:37.9639688Z remote: Compressing objects:  69% (16/23)        
2022-03-06T15:28:37.9639982Z remote: Compressing objects:  73% (17/23)        
2022-03-06T15:28:37.9640315Z remote: Compressing objects:  78% (18/23)        
2022-03-06T15:28:37.9640614Z remote: Compressing objects:  82% (19/23)        
2022-03-06T15:28:37.9640917Z remote: Compressing objects:  86% (20/23)        
2022-03-06T15:28:37.9641221Z remote: Compressing objects:  91% (21/23)        
2022-03-06T15:28:37.9641506Z remote: Compressing objects:  95% (22/23)        
2022-03-06T15:28:37.9641812Z remote: Compressing objects: 100% (23/23)        
2022-03-06T15:28:37.9642116Z remote: Compressing objects: 100% (23/23), done.        
2022-03-06T15:28:38.1614498Z remote: Total 25 (delta 1), reused 14 (delta 0), pack-reused 0        
2022-03-06T15:28:38.1730679Z From https://github.com/Kerakis/mtg-art-game
2022-03-06T15:28:38.1731780Z  * [new ref]         688dfd95b901f2e0bc6409843990242107164377 -> origin/main
2022-03-06T15:28:38.1759895Z ##[endgroup]
2022-03-06T15:28:38.1760759Z ##[group]Determining the checkout info
2022-03-06T15:28:38.1761611Z ##[endgroup]
2022-03-06T15:28:38.1762231Z ##[group]Checking out the ref
2022-03-06T15:28:38.1766804Z [command]/usr/bin/git checkout --progress --force -B main refs/remotes/origin/main
2022-03-06T15:28:38.1912133Z Switched to a new branch 'main'
2022-03-06T15:28:38.1912971Z branch 'main' set up to track 'origin/main'.
2022-03-06T15:28:38.1919384Z ##[endgroup]
2022-03-06T15:28:38.1964135Z [command]/usr/bin/git log -1 --format='%H'
2022-03-06T15:28:38.1994324Z '688dfd95b901f2e0bc6409843990242107164377'
2022-03-06T15:28:38.2002872Z ##[group]Removing auth
2022-03-06T15:28:38.2006360Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2022-03-06T15:28:38.2040678Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2022-03-06T15:28:38.2292224Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2022-03-06T15:28:38.2308274Z http.https://github.com/.extraheader
2022-03-06T15:28:38.2319490Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2022-03-06T15:28:38.2359887Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2022-03-06T15:28:38.2619100Z ##[endgroup]
2022-03-06T15:28:38.2810809Z ##[group]Run JamesIves/fetch-api-data-action@v2.2.0
2022-03-06T15:28:38.2811090Z with:
2022-03-06T15:28:38.2811360Z   endpoint: https://api.scryfall.com/catalog/card-names
2022-03-06T15:28:38.2811648Z   configuration: { "method": "GET" }
2022-03-06T15:28:38.2811868Z   save-location: assets
2022-03-06T15:28:38.2812111Z   save-name: test
2022-03-06T15:28:38.2812481Z ##[endgroup]
2022-03-06T15:28:38.3600355Z 
2022-03-06T15:28:38.3601962Z     Fetch API Data Action 📦 🚚
2022-03-06T15:28:38.3602588Z 
2022-03-06T15:28:38.3603281Z     💖 Support: https://github.com/sponsors/JamesIves
2022-03-06T15:28:38.3604368Z     📣 Maintained by James Ives: https://jamesiv.es
2022-03-06T15:28:38.3605488Z 
2022-03-06T15:28:38.3606085Z     🚀 Getting Started Guide: https://github.com/JamesIves/fetch-api-data-action
2022-03-06T15:28:38.3606942Z     ❓ Discussions / Q&A: https://github.com/JamesIves/fetch-api-data-action/discussions
2022-03-06T15:28:38.3608043Z     🔧 Report a Bug: https://github.com/JamesIves/fetch-api-data-action/issues
2022-03-06T15:28:38.3609179Z Checking configuration and initializing… 🚚
2022-03-06T15:28:38.3656245Z Fetching the requested data… 📦
2022-03-06T15:28:38.8943692Z Saving the data... 📁
2022-03-06T15:28:38.8978008Z Saved assets/test.json 💾
2022-03-06T15:28:38.9011240Z The data was succesfully retrieved and saved! ✅ 🚚
2022-03-06T15:28:38.9147213Z ##[group]Run JamesIves/github-pages-deploy-action@v4.2.5
2022-03-06T15:28:38.9147586Z with:
2022-03-06T15:28:38.9147800Z   branch: main
2022-03-06T15:28:38.9148498Z   folder: assets
2022-03-06T15:28:38.9148734Z   target-folder: assets
2022-03-06T15:28:38.9149317Z   token: ***
2022-03-06T15:28:38.9149591Z   clean: true
2022-03-06T15:28:38.9149818Z env:
2022-03-06T15:28:38.9793455Z   fetch-api-data: **I HAD TO PRUNE THIS IN ORDER TO MEET THE MAXIMUM CHARACTER COUNT OF GITHUB**
2022-03-06T15:28:39.0382291Z ##[endgroup]
2022-03-06T15:28:39.0618581Z ##[error]An error occurred trying to start process '/home/runner/runners/2.288.1/externals/node12/bin/node' with working directory '/home/runner/work/mtg-art-game/mtg-art-game'. Argument list too long
2022-03-06T15:28:39.0673859Z Post job cleanup.
2022-03-06T15:28:39.0705664Z ##[error]An error occurred trying to start process '/home/runner/runners/2.288.1/externals/node12/bin/node' with working directory '/home/runner/work/mtg-art-game/mtg-art-game'. Argument list too long
2022-03-06T15:28:39.0829196Z Cleaning up orphan processes

**Comment by JamesIves** [comment]
Ah yes, this is certainly a bug. It's because it's trying to save the string returned from your API as an output. Your API response is very large which is ultimately causing this but I think we can work around this. 

I think it's best that variable exporting is considered optional as it's possible to fail when API responses are massive and there's not really a finite way to really figure out the maximum allowed amount. This is of course something that we can return to later should the need arise but I think this will solve these odd edge cases while still making the action usable for most people. 

In the meantime can test this configuration? The specific differences are pointing the action to `releases/v2` with the parameter: `set-output: false`. In order to prevent breaking changes `set-output` will default to `true`. 

```yml

      - name: Fetch API Data 📦
        uses: JamesIves/fetch-api-data-action@releases/v2
        with:
          endpoint: https://api.scryfall.com/catalog/card-names
          configuration: '{ "method": "GET" }'
          save-location: assets
          save-name: test
          set-output: false
```

If this works for you I will promote the build to an actual version number once I get back to my computer.

**Comment by Kerakis** [comment]
Unfortunately, I get the same `Argument list too long` error during Post Checkout as before.

**Comment by JamesIves** [comment]
Can you share your updated workflow file? 

**Edit**: Also can you try checkout@v3 just so we cover all bases? You may also want to try adding the following between checkout & fetch-data.

```
    - uses: actions/setup-node@v3
        with:
          node-version: 'v14.18.1'
          registry-url: 'https://registry.npmjs.org'
```

I'm wondering if the checkout step is doing something under the hood that is not expected. In the meantime, I've opened up a ticket upstream with GitHub in case this is something caused by the runner: https://github.com/actions/runner/issues/1733 

Certainly an obscure error but I think I've done everything I can on my end 😢 - In the interim however it looks like your workflow _will_ work, it will just provide a false-negative result.

**Comment by Kerakis** [comment]
```
name: Update Card Names Catalog Test
on:
  schedule:
    - cron: 0 0 * * SUN
     # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  update-cards:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 'v14.18.1'
        registry-url: 'https://registry.npmjs.org'
          
    - name: Fetch API Data 📦
      uses: JamesIves/fetch-api-data-action@releases/v2
      with:
        endpoint: https://api.scryfall.com/catalog/card-names
        configuration: '{ "method": "GET" }'
        save-location: assets
        save-name: test
        set-output: false
        
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: main # Pushes the updates to the main branch.
        folder: assets # The location of the data.json file saved by the Fetch API Data action.
        target-folder: assets # Saves the data into the 'data' directory on the main branch.
        
        
      

```
Still getting the same error with this workflow. Let me know if I messed anything up there.

I appreciate you looking into it and giving it a shot. It isn't a big deal, if I can't get it working.
